-- MySQL Script generated by MySQL Workbench
-- Tue Apr 13 16:33:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `index` INT NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `start` TIME NOT NULL,
  `end` TIME NOT NULL,
  PRIMARY KEY (`index`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`postman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`postman` (
  `idpostman` INT NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `subdistrict_idsubdistrict` INT NOT NULL,
  PRIMARY KEY (`idpostman`),
  INDEX `fk_postman_subdistrict_idx` (`subdistrict_idsubdistrict` ASC) VISIBLE,
  CONSTRAINT `fk_postman_subdistrict`
    FOREIGN KEY (`subdistrict_idsubdistrict`)
    REFERENCES `mydb`.`post` (`index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscriber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscriber` (
  `idsubscriber` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `house` INT NOT NULL,
  `apartment` INT NULL,
  `subdistrict_idsubdistrict` INT NOT NULL,
  PRIMARY KEY (`idsubscriber`),
  INDEX `fk_subscriber_subdistrict1_idx` (`subdistrict_idsubdistrict` ASC) VISIBLE,
  CONSTRAINT `fk_subscriber_subdistrict1`
    FOREIGN KEY (`subdistrict_idsubdistrict`)
    REFERENCES `mydb`.`post` (`index`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`edition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`edition` (
  `idedition` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`idedition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscribtion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscribtion` (
  `idsubscribe` INT NOT NULL,
  `price` INT NOT NULL,
  `term` INT NOT NULL,
  `start` DATE NOT NULL,
  `finish` DATE NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `edition_idedition` INT NOT NULL,
  PRIMARY KEY (`idsubscribe`),
  INDEX `fk_subscribtion_edition1_idx` (`edition_idedition` ASC) VISIBLE,
  CONSTRAINT `fk_subscribtion_edition1`
    FOREIGN KEY (`edition_idedition`)
    REFERENCES `mydb`.`edition` (`idedition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscriber_has_subscribe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscriber_has_subscribe` (
  `subscriber_idsubscriber` INT NOT NULL,
  `subscribe_idsubscribe` INT NOT NULL,
  PRIMARY KEY (`subscriber_idsubscriber`, `subscribe_idsubscribe`),
  INDEX `fk_subscriber_has_subscribe_subscribe1_idx` (`subscribe_idsubscribe` ASC) VISIBLE,
  INDEX `fk_subscriber_has_subscribe_subscriber1_idx` (`subscriber_idsubscriber` ASC) VISIBLE,
  CONSTRAINT `fk_subscriber_has_subscribe_subscriber1`
    FOREIGN KEY (`subscriber_idsubscriber`)
    REFERENCES `mydb`.`subscriber` (`idsubscriber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscriber_has_subscribe_subscribe1`
    FOREIGN KEY (`subscribe_idsubscribe`)
    REFERENCES `mydb`.`subscribtion` (`idsubscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
